apiVersion: v1
kind: Service
metadata:
  name: {{ template "dante.fullname" . }}
  labels:
    app: {{ template "dante.name" . }}
    chart: {{ template "dante.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "dante.name" . }}
    release: {{ .Release.Name }}
